const bcrypt = require("bcryptjs");
const { saveCollection } = require("./db");

const DEMO_USER_ID = "user_demo_001";

const demoUser = {
  id: DEMO_USER_ID,
  name: "Arun Kumar",
  email: "arun@example.com",
  password: "$2a$10$e3hcpqYBNL3pgc9e6jsGKeSzCBSu7F8v513KWliZMT6wDZjhZUzfu", // password123
  avatar: null,
  createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
};

const demoMemories = [
  {
    id: "mem_1",
    userId: DEMO_USER_ID,
    title: "Interview at TechCorp",
    content: "My interview is on July 15 at 10am. Senior Frontend Developer role. Prepare DSA and system design.",
    type: "text",
    category: "Work",
    tags: ["interview", "career", "tech"],
    importance: "high",
    pinned: true,
    date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    deleted: false,
    deletedAt: null,
    vaultId: null,
  },
  {
    id: "mem_2",
    userId: DEMO_USER_ID,
    title: "Project Submission",
    content: "Submitted the capstone project proposal. Professor gave positive feedback. Next milestone is the prototype by August 1st.",
    type: "text",
    category: "Education",
    tags: ["project", "college", "milestone"],
    importance: "medium",
    pinned: true,
    date: new Date(Date.now() - 365 * 24 * 60 * 60 * 1000).toISOString(),
    deleted: false,
    deletedAt: null,
    vaultId: null,
  },
  {
    id: "mem_3",
    userId: DEMO_USER_ID,
    title: "Passport Renewal",
    content: "Passport expires December 2025. Renew 6 months before. Need: old passport, 2 photos, application form, proof of address.",
    type: "text",
    category: "Personal",
    tags: ["passport", "documents", "urgent"],
    importance: "high",
    pinned: true,
    date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    deleted: false,
    deletedAt: null,
    vaultId: null,
  },
  {
    id: "mem_4",
    userId: DEMO_USER_ID,
    title: "Met John at Symposium",
    content: "Met John at the AI symposium. He works at DeepMind. Discussed collaboration on an NLP project.",
    type: "text",
    category: "Network",
    tags: ["john", "networking", "AI"],
    importance: "medium",
    pinned: false,
    date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    deleted: false,
    deletedAt: null,
    vaultId: null,
    relatedPerson: "John",
  },
  {
    id: "mem_5",
    userId: DEMO_USER_ID,
    title: "AI Project Discussion with Priya",
    content: "Brainstormed ideas for the AI project. Focused on sentiment analysis for Tamil literature. Priya handles data pipeline, I work on the model.",
    type: "text",
    category: "Work",
    tags: ["AI", "priya", "project"],
    importance: "high",
    pinned: false,
    date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    deleted: false,
    deletedAt: null,
    vaultId: null,
    relatedPerson: "Priya",
  },
  {
    id: "mem_6",
    userId: DEMO_USER_ID,
    title: "Morning Routine Checklist",
    content: "",
    type: "checklist",
    category: "Personal",
    tags: ["routine", "daily", "health"],
    importance: "low",
    pinned: false,
    checklist: [
      { id: "c1", text: "Wake up at 6am", done: true },
      { id: "c2", text: "Meditate for 10 minutes", done: true },
      { id: "c3", text: "Exercise 30 minutes", done: false },
      { id: "c4", text: "Cold shower", done: false },
      { id: "c5", text: "Journal entry", done: false },
    ],
    date: new Date().toISOString(),
    deleted: false,
    deletedAt: null,
    vaultId: null,
  },
  {
    id: "mem_7",
    userId: DEMO_USER_ID,
    title: "Voice Note \u2013 Project Ideas",
    content: "Voice note discussing semester project ideas including mobile app concepts.",
    type: "voice",
    category: "Work",
    tags: ["voice", "ideas", "project"],
    importance: "medium",
    pinned: false,
    duration: "2:34",
    date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    deleted: false,
    deletedAt: null,
    vaultId: null,
  },
  {
    id: "mem_8",
    userId: DEMO_USER_ID,    title: "Birthday",
    content: "24th nov is my birthday.",
    type: "text",
    category: "Personal",
    tags: ["birthday", "personal"],
    importance: "medium",
    pinned: true,
    date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    deleted: false,
    deletedAt: null,
    vaultId: null,
  },
  {
    id: "mem_9",
    userId: DEMO_USER_ID,    title: "Conference Photo Memory",
    content: "Photo taken at the annual tech conference with the team.",
    type: "image",
    category: "Personal",
    tags: ["photo", "conference", "team"],
    importance: "low",
    pinned: false,
    date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    deleted: false,
    deletedAt: null,
    vaultId: null,
  },
  {
    id: "mem_10",
    userId: DEMO_USER_ID,
    title: "Old Brainstorm Notes",
    content: "Old brainstorming ideas no longer relevant.",
    type: "text",
    category: "Personal",
    tags: [],
    importance: "low",
    pinned: false,
    date: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
    deleted: true,
    deletedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    vaultId: null,
  },
];

const demoPeople = [
  {
    id: "p1",
    userId: DEMO_USER_ID,
    name: "John",
    phone: "+91 98765 43210",
    email: "john@deepmind.com",
    birthday: "1992-03-15",
    lastInteraction: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    notes: "Works at DeepMind. Expert in transformers and NLP.",
    relatedMemoryIds: ["mem_4"],
    avatar: null,
  },
  {
    id: "p2",
    userId: DEMO_USER_ID,
    name: "Priya",
    phone: "+91 87654 32109",
    email: "priya@example.com",
    birthday: "1995-07-22",
    lastInteraction: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    notes: "Collaborator on AI project. Expert in data pipelines.",
    relatedMemoryIds: ["mem_5"],
    avatar: null,
  },
  {
    id: "p3",
    userId: DEMO_USER_ID,
    name: "Rahul",
    phone: "+91 76543 21098",
    email: "rahul@example.com",
    birthday: "1993-11-08",
    lastInteraction: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    notes: "College friend. Now at Flipkart as a product manager.",
    relatedMemoryIds: [],
    avatar: null,
  },
  {
    id: "p4",
    userId: DEMO_USER_ID,
    name: "Arjun",
    phone: "+91 65432 10987",
    email: "arjun@example.com",
    birthday: "1994-05-30",
    lastInteraction: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    notes: "Met at hackathon. Full-stack developer.",
    relatedMemoryIds: [],
    avatar: null,
  },
];

async function seedData() {
  await saveCollection("users", [demoUser]);
  await saveCollection("memories", demoMemories);
  await saveCollection("people", demoPeople);
  await saveCollection("vaults", [
    {
      id: "vault_demo_001",
      userId: DEMO_USER_ID,
      password: bcrypt.hashSync("vault123", 10),
      locked: false,
      createdAt: new Date().toISOString(),
    },
  ]);
}

if (require.main === module) {
  seedData();
  console.log("Seed data created successfully!");
}

module.exports = { seedData, demoUser, demoMemories, demoPeople };
